[package]
name = "shodokan"
version = "0.1.0"
authors = ["Matt DeBoard <matt.deboard@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
